<?php
/**
 * ==========================================================================
 * admin/change-password.php — Force First-Login Admin Password Update
 * ==========================================================================
 * Mandatory password initialization form for administrators logging in with
 * a temporary one-time password generated by Super Admin.
 * Enforces strong password complexity (12+ chars, uppercase, lowercase,
 * numbers, and special symbols).
 * ==========================================================================
 */

declare(strict_types=1);

require_once __DIR__ . '/../public/dbconnect.php';
require_once __DIR__ . '/middleware/auth_middleware.php';

// Verify admin is logged in
if (!is_admin_logged_in()) {
    redirect_to_admin_login();
}

$admin = current_admin();
if (!$admin) {
    admin_logout();
    redirect_to_admin_login();
}

$pdo = db();
$error = null;
$success = null;

if (method_is('post')) {
    if (!verify_csrf()) {
        $error = 'Invalid security request (CSRF check failed).';
    } else {
        $newPassword = (string) input('new_password', '');
        $confirmPassword = (string) input('confirm_password', '');

        // 1. Password complexity validation (12+ chars, upper, lower, number, symbol)
        if (strlen($newPassword) < 12) {
            $error = 'Your new password must be at least 12 characters in length.';
        } elseif (!preg_match('/[A-Z]/', $newPassword)) {
            $error = 'Your password must include at least one uppercase letter (A-Z).';
        } elseif (!preg_match('/[a-z]/', $newPassword)) {
            $error = 'Your password must include at least one lowercase letter (a-z).';
        } elseif (!preg_match('/[0-9]/', $newPassword)) {
            $error = 'Your password must include at least one number (0-9).';
        } elseif (!preg_match('/[^A-Za-z0-9]/', $newPassword)) {
            $error = 'Your password must include at least one special character (!@#$%^&* etc.).';
        } elseif ($newPassword !== $confirmPassword) {
            $error = 'New password and confirmation password do not match.';
        } else {
            try {
                $newHash = password_hash($newPassword, PASSWORD_DEFAULT);

                $stmt = $pdo->prepare('
                    UPDATE admins SET 
                        password = :hash,
                        must_change_password = 0,
                        password_changed_at = NOW(),
                        remember_token = NULL,
                        updated_at = NOW()
                    WHERE id = :id
                ');
                $stmt->execute([
                    'hash' => $newHash,
                    'id'   => (int) $admin['id'],
                ]);

                // Regenerate session ID
                session_regenerate_id(true);

                // Log password change event
                log_admin_activity('password_changed', 'Administrator initialized/updated password successfully');

                flash('admin_msg', 'Your password has been successfully updated. Welcome to GroCo Admin!', 'success');
                redirect_admin('index.php');
            } catch (PDOException $e) {
                error_log('[change-password] Update failed: ' . $e->getMessage());
                $error = 'Failed to update password due to server database error.';
            }
        }
    }
}

$pageTitle = 'Set New Password — GroCo Admin';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= e($pageTitle) ?></title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="<?= BASE_URL ?>/../admin/assets/css/admin.css">
    <style>
        .password-change-wrapper {
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: var(--color-bg);
            padding: 20px;
        }
        .password-change-card {
            background-color: var(--color-surface);
            border: 1px solid var(--color-border);
            border-radius: var(--radius-lg);
            box-shadow: 0 10px 30px rgba(0,0,0,0.1);
            max-width: 480px;
            width: 100%;
            padding: 36px 32px;
            box-sizing: border-box;
        }
        .pw-req-list {
            margin: 12px 0;
            padding-left: 20px;
            font-size: 12px;
            color: var(--color-text-muted);
            line-height: 1.6;
        }
    </style>
</head>
<body>
<div class="password-change-wrapper">
    <div class="password-change-card">
        <div style="text-align:center; margin-bottom: 24px;">
            <div style="width: 56px; height: 56px; border-radius: 50%; background: #e6fcf5; color: #0ca678; display: inline-flex; align-items: center; justify-content: center; font-size: 24px; margin-bottom: 12px;">
                <i class="fas fa-key"></i>
            </div>
            <h1 style="font-size: 20px; font-weight: 800; color: var(--color-text); margin: 0 0 6px 0;">Set Your Permanent Password</h1>
            <p style="font-size: 13px; color: var(--color-text-muted); margin: 0;">
                Your temporary one-time password has been verified. Please create a strong permanent password to access the administrative portal.
            </p>
        </div>

        <?php if ($error !== null): ?>
            <div style="background:#fff5f5; border:1px solid #ffe3e3; color:#e03131; padding:12px; border-radius:var(--radius-sm); font-size:13px; font-weight:600; margin-bottom: 20px;">
                <i class="fas fa-circle-exclamation" style="margin-right:6px;"></i> <?= e($error) ?>
            </div>
        <?php endif; ?>

        <form method="post" action="change-password.php">
            <?= csrf_field() ?>

            <div style="margin-bottom: 16px;">
                <label style="display:block; font-size: 12px; font-weight: 700; text-transform: uppercase; color: var(--color-text); margin-bottom: 6px;">New Password *</label>
                <input type="password" name="new_password" id="new_password" required autofocus placeholder="Enter at least 12 characters" style="width:100%; padding: 10px 14px; border: 1px solid var(--color-border); border-radius: var(--radius-sm); background: var(--color-bg); color: var(--color-text); font-size: 14px; box-sizing: border-box;">
            </div>

            <div style="margin-bottom: 16px;">
                <label style="display:block; font-size: 12px; font-weight: 700; text-transform: uppercase; color: var(--color-text); margin-bottom: 6px;">Confirm New Password *</label>
                <input type="password" name="confirm_password" id="confirm_password" required placeholder="Re-type new password" style="width:100%; padding: 10px 14px; border: 1px solid var(--color-border); border-radius: var(--radius-sm); background: var(--color-bg); color: var(--color-text); font-size: 14px; box-sizing: border-box;">
            </div>

            <div style="background: var(--color-bg); border: 1px solid var(--color-border); border-radius: var(--radius-sm); padding: 12px 16px; margin-bottom: 20px;">
                <strong style="font-size: 12px; color: var(--color-text);">Password Requirements:</strong>
                <ul class="pw-req-list">
                    <li>Minimum 12 characters in length</li>
                    <li>At least one uppercase letter (A-Z)</li>
                    <li>At least one lowercase letter (a-z)</li>
                    <li>At least one number (0-9)</li>
                    <li>At least one special character (!@#$%^&* etc.)</li>
                </ul>
            </div>

            <button type="submit" class="btn btn-primary" style="width:100%; padding: 12px; font-weight: 800; font-size: 14px; border-radius: var(--radius-pill); border: none; cursor: pointer;">
                Update Password & Enter Admin &rarr;
            </button>
        </form>

        <div style="text-align:center; margin-top: 20px;">
            <a href="logout.php" style="color: var(--color-text-muted); font-size: 12px; text-decoration: none;">
                <i class="fas fa-arrow-right-from-bracket"></i> Sign out and change later
            </a>
        </div>
    </div>
</div>
</body>
</html>
